version: '2.3'
services:
  app:
    image: my127/php:7.2-fpm-stretch-console
    working_dir: "/app"
    env_file:
      - .env
    volumes:
      - ".:/app:delegated"

  webserver:
    build: docker/nginx
    volumes:
      - ".:/app:delegated"
    ports:
      - 8080:80
    links:
      - app:app
